### ISSUE TITLE
How to change the style?

### ISSUE THREAD

**Issue by youjiaa** [the-wrong-guy/read-more-more#1]
Hi, I was using this package and I noticed the line height was set to 20px by default. I try to apply a prebuild css class on it but it's not working. And I didn't find the class this tag is using. So how can I change the style of the text?

**Comment by the-wrong-guy** [comment]
> Hi, I was using this package and I noticed the line height was set to 20px by default. I try to apply a prebuild css class on it but it's not working. And I didn't find the class this tag is using. So how can I change the style of the text?

Hey i don't remember that I added anything to change the styles of the text, did you tried "style" prop, if it's not there I will add props to change the styles by tomorrow.

**Comment by the-wrong-guy** [comment]
Add to `AdvReadMoreMore`
