### ISSUE TITLE
checkFor value

### ISSUE THREAD

**Issue by alexjslater** [the-wrong-guy/read-more-more#2]
Currently checkFor value is not being passed, might be an issue on how we are supposed to "write" this value

<AdvReadMoreMore checkFor={100} text={abstract} />

Can you advise?

**Comment by the-wrong-guy** [comment]
> Currently checkFor value is not being passed, might be an issue on how we are supposed to "write" this value
> 
> Can you advise?

Hey, thanks for your query, it was a logic and type error and I have pushed a fix for that, please download the latest version. And `checkFor` takes a `number` as an argument, so provide a number for that

**Comment by the-wrong-guy** [comment]
fixed
